// File generated by FlutterFire CLI.
// This is a PLACEHOLDER file - will be replaced after Firebase setup
// Run: flutterfire configure

// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER - Replace with your Firebase project config

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCHNBY4WLlkGsKYYJV37er6bXxJcaFzgI',
    appId: '1:928459636135:web:de9179b56b8e254f8e4a82',
    messagingSenderId: '928459636135',
    projectId: 'self-order-7f581',
    authDomain: 'self-order-7f581.firebaseapp.com',
    storageBucket: 'self-order-7f581.firebasestorage.app',
  );

  // After running: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZTSoSC4cVcK-LvEyP37bfYVK9o65Pnw',
    appId: '1:928459636135:android:9f87b467448da6558e4a82',
    messagingSenderId: '928459636135',
    projectId: 'self-order-7f581',
    storageBucket: 'self-order-7f581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHxdlcF1XtdfiqP-xMsLcS0oDK882REo4',
    appId: '1:928459636135:ios:aca77c084266d27f8e4a82',
    messagingSenderId: '928459636135',
    projectId: 'self-order-7f581',
    storageBucket: 'self-order-7f581.firebasestorage.app',
    iosBundleId: 'com.example.flutterPosrestoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: '1:YOUR_PROJECT_ID:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.yourcompany.posresto',
  );
}